apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-pod
  template:
    metadata:
      labels:
        app: mongo-pod
    spec:
      serviceAccountName: bsc-ssd-y4-2025-sa
      containers:
      - image: bitnami/mongodb:latest
        name: mongo
        env:
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: password
              name: mongodb-config
        - name: MONGODB_ROOT_USER
          valueFrom:
            configMapKeyRef:
              key: username
              name: mongodb-config
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /bitnami/mongodb
          name: mongo-volume
        - mountPath: /bitnami
          name: mongo-config-test
      volumes:
      - name: mongo-volume
        persistentVolumeClaim:
          claimName: mongo-pvc-sc
      - name: mongo-config-test
        configMap:
          name: mongodb-config
          items:
          - key: sample.conf
            path: test.conf
